# Generated by Django 4.2.7 on 2023-11-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_alter_userprofile_email_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
