# Generated by Django 4.2.7 on 2023-11-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
