# Generated by Django 4.2.7 on 2023-11-21 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "userProfile",
            "0009_alter_userprofile_groups_alter_userprofile_password_and_more",
        ),
    ]

    operations = [
        # Remove options and managers
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.AlterModelManagers(
            name="userprofile",
            managers=[],
        ),
        # Remove unnecessary fields
        migrations.RemoveField(
            model_name="userprofile",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="password",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="username",
        ),
        # Add the new OneToOneField
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
